#!/bin/sh

# Dependencies:
# magick (ImageMagick 7), wal, xdotool, xwallpaper

wall_dir=~/Pictures/wallpapers

if [ -z "$1" ]; then
  wall="$(find "$wall_dir" -type f -name "*.jpg" -o -name "*.png" | shuf -n 1)"
else
  wall="$1"
fi

# Use 'magick' instead of 'convert'
magick "$wall" ~/.local/share/bg.jpg

xwallpaper --zoom ~/.local/share/bg.jpg
wal -c
wal -i ~/.local/share/bg.jpg

xdotool key super+F5
